package common

import (
	"errors"
	"path/filepath"
	"strings"
	"testing"
)

// startSessionWithMaps gives a test the remap maps a real conversion would have
// generated by the time EncodeVideo runs.
func startSessionWithMaps(t *testing.T, video *VideoSpecs, squeeze bool) {
	t.Helper()

	if err := InitEncodingSession(nil); err != nil {
		t.Fatalf("failed to init session: %v", err)
	}
	t.Cleanup(func() {
		if err := CleanUp(); err != nil {
			t.Errorf("failed to clean up session: %v", err)
		}
	})

	if err := GeneratePGM(video, squeeze); err != nil {
		t.Fatalf("failed to generate the remap maps: %v", err)
	}
}

// TestSessionOutputSize_ReadsWhatGeneratePGMWrote ties the reading to the
// writing. The maps are the conversion's own statement of the frame it is
// producing, which is why the fallback prices them rather than recomputing a
// geometry it would have to be handed the squeeze flag to derive.
func TestSessionOutputSize_ReadsWhatGeneratePGMWrote(t *testing.T) {
	video := hevcSource("yuv420p10le")

	for _, squeeze := range []bool{false, true} {
		t.Run(map[bool]string{false: "widened", true: "un-squeezed"}[squeeze], func(t *testing.T) {
			startSessionWithMaps(t, video, squeeze)

			wantX, wantY := remapOutputSize(video, squeeze)
			gotX, gotY, ok := sessionOutputSize()

			if !ok {
				t.Fatal("the maps were just written, so their size must be readable")
			}
			if gotX != wantX || gotY != wantY {
				t.Fatalf("read %dx%d from the maps, but GeneratePGM wrote %dx%d", gotX, gotY, wantX, wantY)
			}
		})
	}
}

func TestSessionOutputSize_SaysSoWithoutASession(t *testing.T) {
	if err := CloseEncodingSession(); err != nil {
		t.Fatalf("failed to close any open session: %v", err)
	}

	if _, _, ok := sessionOutputSize(); ok {
		t.Fatal("with no session there is no map to read, and no size to report")
	}
}

// TestEncodeVideo_RefusesAFallbackThatCannotFitInMemory is the hole this closes.
//
// PerformEncoding's guard is shown the encoder selected at the start. When that
// is a hardware encoder it declines to estimate -- correctly, none has been
// measured. But the encoder arriving at the fallback is a software one, and on
// the machine that produced this finding it is the expensive one: libx265 at
// 6.2 GB on a laptop with 8, which is how the kernel came to kill ffmpeg.
func TestEncodeVideo_RefusesAFallbackThatCannotFitInMemory(t *testing.T) {
	video := hevcSource("yuv420p10le")
	startSessionWithMaps(t, video, false)

	dir := t.TempDir()
	fakeRefusingFFmpeg(t, dir, filepath.Join(dir, "calls.txt"))
	launches := countFFmpegLaunches(t)

	withAvailableMemory(t, 1*gib, true)

	err := EncodeVideo(nil, video, "h264_vaapi", 2_000_000,
		filepath.Join(t.TempDir(), "out.mp4"), vaapiMachine, func(float64) {}, make(chan struct{}))

	if err == nil {
		t.Fatal("expected the conversion to be refused")
	}
	var encoderErr *EncoderError
	if !errors.As(err, &encoderErr) {
		t.Fatalf("expected the memory refusal, got %T: %v", err, err)
	}
	if !strings.Contains(err.Error(), "not enough memory") {
		t.Fatalf("the refusal must name the reason, got: %v", err)
	}
	if !strings.Contains(err.Error(), "libx265") {
		t.Fatalf("the refusal must name the encoder that would have run, got: %v", err)
	}

	// Two attempts with the hardware encoder -- hardware decode, then CPU
	// decode -- and then nothing. The third launch is the one that would have
	// been killed.
	if got := launches.Load(); got != 2 {
		t.Fatalf("ffmpeg was launched %d times; the fallback should never have started", got)
	}
}

// TestEncodeVideo_FallbackProceedsWhenMemoryAllows is the other half: the check
// must not stand in the way of the fallback it was added to guard. Without this,
// making the refusal unconditional would pass the test above and break every
// machine that had room.
func TestEncodeVideo_FallbackProceedsWhenMemoryAllows(t *testing.T) {
	video := hevcSource("yuv420p10le")
	startSessionWithMaps(t, video, false)

	dir := t.TempDir()
	fakeRefusingFFmpeg(t, dir, filepath.Join(dir, "calls.txt"))
	launches := countFFmpegLaunches(t)

	withAvailableMemory(t, 64*gib, true)

	err := EncodeVideo(nil, video, "h264_vaapi", 2_000_000,
		filepath.Join(t.TempDir(), "out.mp4"), vaapiMachine, func(float64) {}, make(chan struct{}))

	if err == nil {
		t.Fatal("the stand-in ffmpeg fails every time, so an error was expected")
	}
	if strings.Contains(err.Error(), "not enough memory") {
		t.Fatalf("64 GB is ample; the fallback must not be refused: %v", err)
	}
	if got := launches.Load(); got != 3 {
		t.Fatalf("ffmpeg was launched %d times, want 3: two hardware attempts and the CPU fallback", got)
	}
}
